# This is a basic workflow to help you get started with Actions

name: Fastlane1

# Controls when the workflow will run
on:
  # pull_request: 
  #  branches:
  #  - development
  #  types: [opened, synchronize, reopened]
  push:
   branches: ['SET-LATTER']
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Fastlane2
    runs-on: macos-12
    # macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      # - name: Force XCode 13.3
      #  run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
      # - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '13.3'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'tests'
          bundle-install-path: 'vendor/bundle'
